version: '2'
services:
  mediary:
    image: ghcr.io/dir01/mediary:latest
    ports:
      - "8700:8700"
    environment:
      - REDIS_URL=redis://redis:6379
      - BIND_ADDR=0.0.0.0:8700
    depends_on:
      redis:
        condition: service_healthy
      s3:
        condition: service_healthy

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  s3:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566']

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus exporter
    depends_on:
      - jaeger
      - prometheus
